#!/usr/bin/env python3
"""Fetch real road geometry for the trip's road legs from the OSRM public
demo server and write it to road-geometry.js.

Runs in CI (GitHub Actions runner has open internet). No API key required.

Output: window.ROAD_GEOMETRY = { "<from>→<to>": [[lat,lng], ...], ... }
Keys MUST match map.html exactly: `${seg.from}→${seg.to}` (arrow = U+2192).
A failed segment is simply omitted, so map.html falls back to its waypoints.
"""
import json, sys, time, urllib.request

OSRM = "https://router.project-osrm.org/route/v1/driving/"

# Ordered [lat, lng] waypoints per road leg. Intermediate points steer OSRM
# onto the intended corridor; OSRM snaps everything to the real road network.
ROADS = {
    "Istanbul, Türkiye→Çanakkale, Türkiye":
        [[41.0082, 28.9784], [40.978, 27.511], [40.410, 26.673], [40.1553, 26.4142]],
    "Çanakkale, Türkiye→Mount Ida (Kaz Dağı)":
        [[40.1553, 26.4142], [39.790, 26.337], [39.7167, 26.8500]],
    "Mount Ida (Kaz Dağı)→Cunda (Ayvalık)":
        [[39.7167, 26.8500], [39.595, 27.018], [39.3370, 26.6580]],
    "Cunda (Ayvalık)→Sığacık, Türkiye":
        [[39.3370, 26.6580], [38.930, 26.935], [38.492, 26.974], [38.1969, 26.7869]],
    "Sığacık, Türkiye→İzmir, Türkiye":
        [[38.1969, 26.7869], [38.323, 26.764], [38.4237, 27.1428]],
    "İzmir, Türkiye→Çeşme, Türkiye":
        [[38.4237, 27.1428], [38.323, 26.764], [38.3234, 26.3008]],
    "Heraklion, Crete→Chania, Crete":
        [[35.3387, 25.1442], [35.366, 24.474], [35.5138, 24.0180]],
    "Bilbao, Spain→Picos de Europa":
        [[43.2630, -2.9350], [43.1937, -4.8406]],
    "Picos de Europa→Pamplona, Spain":
        [[43.1937, -4.8406], [42.8125, -1.6458]],
    "Pamplona, Spain→San Sebastián (Donostia)":
        [[42.8125, -1.6458], [43.3183, -1.9812]],
    "San Sebastián (Donostia)→Bilbao — fly out":
        [[43.3183, -1.9812], [43.2950, -2.9100]],
}


def fetch(waypoints):
    coord_str = ";".join(f"{lng},{lat}" for lat, lng in waypoints)
    url = f"{OSRM}{coord_str}?overview=full&geometries=geojson"
    for attempt in range(4):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "odyssey-trip-roadbuilder"})
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.load(resp)
            if data.get("code") != "Ok":
                raise RuntimeError(f"OSRM code={data.get('code')}")
            line = data["routes"][0]["geometry"]["coordinates"]  # [lng, lat] pairs
            return [[round(lat, 5), round(lng, 5)] for lng, lat in line]
        except Exception as e:
            print(f"  attempt {attempt + 1} failed: {e}", file=sys.stderr)
            time.sleep(2 * (attempt + 1))
    return None


def main():
    out = {}
    for key, wps in ROADS.items():
        print(f"routing {key} ...")
        geo = fetch(wps)
        if geo:
            out[key] = geo
            print(f"  ok — {len(geo)} points")
        else:
            print(f"  FAILED — map.html will fall back to waypoints")
        time.sleep(1.2)  # be polite to the public demo server

    js = ("// AUTO-GENERATED by scripts/build_roads.py (GitHub Actions). Do not edit by hand.\n"
          "window.ROAD_GEOMETRY = "
          + json.dumps(out, ensure_ascii=False, separators=(",", ":"))
          + ";\n")
    with open("road-geometry.js", "w", encoding="utf-8") as f:
        f.write(js)
    print(f"wrote road-geometry.js with {len(out)}/{len(ROADS)} routes")
    if not out:
        sys.exit("no routes fetched — refusing to overwrite with empty data")


if __name__ == "__main__":
    main()
